### ISSUE TITLE
More complex presence tracks

### ISSUE THREAD

**Issue by SteveBallantine** [Gudradain/spirit-island-template#28]
Hi, great work on these templates. 
We've already created some custom spirits on paper and this makes them look a lot more polished.

I am interested in supporting presence tracks that have more complex topography. For example, serpent, or even something more extreme, like finder.

Has anyone already done some work on this?
If not, I'll start playing around and see what I can come up with.

**Comment by LordMotas** [comment]
As far as I can tell no one has started undertaking such an effort. Since non-standard Presence Tracks are the exception rather than the norm, I encourage anyone to come up with what they would use for their own custom Spirit and then implement it such that anyone could do it later.

All in all, go for it!
